// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.VBox vbox1;
    
    private HeadTracking.Room RoomTracker;
    
    private Gtk.Button ConnectBtn;
    
    private Gtk.Button ExitBtn;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize();
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("HeadTracking");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        this.RoomTracker = new HeadTracking.Room();
        this.RoomTracker.Events = ((Gdk.EventMask)(256));
        this.RoomTracker.Name = "RoomTracker";
        this.vbox1.Add(this.RoomTracker);
        Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox1[this.RoomTracker]));
        w1.Position = 0;
        // Container child vbox1.Gtk.Box+BoxChild
        this.ConnectBtn = new Gtk.Button();
        this.ConnectBtn.CanFocus = true;
        this.ConnectBtn.Name = "ConnectBtn";
        this.ConnectBtn.UseUnderline = true;
        this.ConnectBtn.Label = Mono.Unix.Catalog.GetString("Connect");
        this.vbox1.Add(this.ConnectBtn);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.ConnectBtn]));
        w2.Position = 1;
        w2.Expand = false;
        w2.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.ExitBtn = new Gtk.Button();
        this.ExitBtn.CanFocus = true;
        this.ExitBtn.Name = "ExitBtn";
        this.ExitBtn.UseUnderline = true;
        this.ExitBtn.Label = Mono.Unix.Catalog.GetString("Exit");
        this.vbox1.Add(this.ExitBtn);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.ExitBtn]));
        w3.Position = 2;
        w3.Expand = false;
        w3.Fill = false;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 400;
        this.DefaultHeight = 300;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.ConnectBtn.Clicked += new System.EventHandler(this.OnConnectBtnClicked);
        this.ExitBtn.Clicked += new System.EventHandler(this.OnExitBtnClicked);
    }
}
