// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.VBox vbox1;
    
    private GLWii.WiimoteGL WiimoteView;
    
    private Gtk.Button ConnectBtn;
    
    private Gtk.Button CalibrateButton;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize();
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("MainWindow");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        this.WiimoteView = new GLWii.WiimoteGL();
        this.WiimoteView.Events = ((Gdk.EventMask)(256));
        this.WiimoteView.Name = "WiimoteView";
        this.vbox1.Add(this.WiimoteView);
        Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox1[this.WiimoteView]));
        w1.Position = 0;
        // Container child vbox1.Gtk.Box+BoxChild
        this.ConnectBtn = new Gtk.Button();
        this.ConnectBtn.CanFocus = true;
        this.ConnectBtn.Name = "ConnectBtn";
        this.ConnectBtn.UseUnderline = true;
        this.ConnectBtn.Label = Mono.Unix.Catalog.GetString("Connect");
        this.vbox1.Add(this.ConnectBtn);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.ConnectBtn]));
        w2.Position = 1;
        w2.Expand = false;
        w2.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.CalibrateButton = new Gtk.Button();
        this.CalibrateButton.CanFocus = true;
        this.CalibrateButton.Name = "CalibrateButton";
        this.CalibrateButton.UseUnderline = true;
        this.CalibrateButton.Label = Mono.Unix.Catalog.GetString("Calibrate");
        this.vbox1.Add(this.CalibrateButton);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.CalibrateButton]));
        w3.Position = 2;
        w3.Expand = false;
        w3.Fill = false;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 441;
        this.DefaultHeight = 354;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.ConnectBtn.Clicked += new System.EventHandler(this.OnConnectBtnClicked);
        this.CalibrateButton.Clicked += new System.EventHandler(this.OnCalibrateButtonClicked);
    }
}
