// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.HPaned hpaned1;
    
    private Gtk.Frame frame2;
    
    private Gtk.Alignment GtkAlignment;
    
    private Gtk.VBox vbox1;
    
    private Gtk.HBox hbox2;
    
    private Gtk.VBox vbox4;
    
    private Gtk.HBox hbox3;
    
    private Gtk.ToggleButton LED1Toggle;
    
    private Gtk.ToggleButton LED2Toggle;
    
    private Gtk.ToggleButton LED3Toggle;
    
    private Gtk.ToggleButton LED4Toggle;
    
    private Gtk.ToggleButton RumbleToggle;
    
    private Gtk.Frame frame4;
    
    private Gtk.Alignment GtkAlignment1;
    
    private Gtk.VBox vbox2;
    
    private Gtk.HBox hbox1;
    
    private Gtk.Label label1;
    
    private Gtk.ProgressBar XAccelBar;
    
    private Gtk.HBox hbox4;
    
    private Gtk.Label label3;
    
    private Gtk.ProgressBar YAccelBar;
    
    private Gtk.HBox hbox5;
    
    private Gtk.Label label4;
    
    private Gtk.ProgressBar ZAccelBar;
    
    private Gtk.Label GtkLabel8;
    
    private Gtk.Statusbar statusbar1;
    
    private Gtk.Label ButtonLabel;
    
    private Gtk.Label StatusLabel;
    
    private Gtk.Button ConnectButton;
    
    private Gtk.Frame frame1;
    
    private Gtk.Alignment GtkAlignment3;
    
    private Gtk.DrawingArea InfraRedArea;
    
    private Gtk.Label GtkLabel7;
    
    private Gtk.Label GtkLabel10;
    
    private Gtk.Frame frame3;
    
    private Gtk.Alignment GtkAlignment2;
    
    private Gtk.VBox vbox3;
    
    private Gtk.Frame frame5;
    
    private Gtk.Alignment GtkAlignment4;
    
    private Gtk.VBox vbox5;
    
    private Gtk.HBox hbox6;
    
    private Gtk.Label label5;
    
    private Gtk.ProgressBar NunchukXAccelBar;
    
    private Gtk.HBox hbox7;
    
    private Gtk.Label label6;
    
    private Gtk.ProgressBar NunchukYAccelBar;
    
    private Gtk.HBox hbox8;
    
    private Gtk.Label label7;
    
    private Gtk.ProgressBar NunchukZAccelBar;
    
    private Gtk.Label GtkLabel11;
    
    private Gtk.Frame frame6;
    
    private Gtk.Alignment GtkAlignment6;
    
    private Gtk.DrawingArea NunchukStickArea;
    
    private Gtk.Label GtkLabel13;
    
    private Gtk.Statusbar statusbar2;
    
    private Gtk.Label NunchukButtonLabel;
    
    private Gtk.Label NunchukStatusLabel;
    
    private Gtk.Label GtkLabel12;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize();
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("MainWindow");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.hpaned1 = new Gtk.HPaned();
        this.hpaned1.CanFocus = true;
        this.hpaned1.Name = "hpaned1";
        this.hpaned1.Position = 487;
        // Container child hpaned1.Gtk.Paned+PanedChild
        this.frame2 = new Gtk.Frame();
        this.frame2.Name = "frame2";
        this.frame2.ShadowType = ((Gtk.ShadowType)(4));
        // Container child frame2.Gtk.Container+ContainerChild
        this.GtkAlignment = new Gtk.Alignment(0F, 0F, 1F, 1F);
        this.GtkAlignment.Name = "GtkAlignment";
        this.GtkAlignment.LeftPadding = ((uint)(12));
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox2 = new Gtk.HBox();
        this.hbox2.Name = "hbox2";
        this.hbox2.Homogeneous = true;
        this.hbox2.Spacing = 6;
        // Container child hbox2.Gtk.Box+BoxChild
        this.vbox4 = new Gtk.VBox();
        this.vbox4.Name = "vbox4";
        this.vbox4.Spacing = 6;
        // Container child vbox4.Gtk.Box+BoxChild
        this.hbox3 = new Gtk.HBox();
        this.hbox3.Name = "hbox3";
        this.hbox3.Spacing = 6;
        // Container child hbox3.Gtk.Box+BoxChild
        this.LED1Toggle = new Gtk.ToggleButton();
        this.LED1Toggle.CanFocus = true;
        this.LED1Toggle.Name = "LED1Toggle";
        this.LED1Toggle.UseUnderline = true;
        this.LED1Toggle.Label = Mono.Unix.Catalog.GetString("LED1");
        this.hbox3.Add(this.LED1Toggle);
        Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox3[this.LED1Toggle]));
        w1.Position = 0;
        w1.Expand = false;
        w1.Fill = false;
        // Container child hbox3.Gtk.Box+BoxChild
        this.LED2Toggle = new Gtk.ToggleButton();
        this.LED2Toggle.CanFocus = true;
        this.LED2Toggle.Name = "LED2Toggle";
        this.LED2Toggle.UseUnderline = true;
        this.LED2Toggle.Label = Mono.Unix.Catalog.GetString("LED2");
        this.hbox3.Add(this.LED2Toggle);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox3[this.LED2Toggle]));
        w2.Position = 1;
        w2.Expand = false;
        w2.Fill = false;
        // Container child hbox3.Gtk.Box+BoxChild
        this.LED3Toggle = new Gtk.ToggleButton();
        this.LED3Toggle.CanFocus = true;
        this.LED3Toggle.Name = "LED3Toggle";
        this.LED3Toggle.UseUnderline = true;
        this.LED3Toggle.Label = Mono.Unix.Catalog.GetString("LED3");
        this.hbox3.Add(this.LED3Toggle);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox3[this.LED3Toggle]));
        w3.Position = 2;
        w3.Expand = false;
        w3.Fill = false;
        // Container child hbox3.Gtk.Box+BoxChild
        this.LED4Toggle = new Gtk.ToggleButton();
        this.LED4Toggle.CanFocus = true;
        this.LED4Toggle.Name = "LED4Toggle";
        this.LED4Toggle.UseUnderline = true;
        this.LED4Toggle.Label = Mono.Unix.Catalog.GetString("LED4");
        this.hbox3.Add(this.LED4Toggle);
        Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox3[this.LED4Toggle]));
        w4.Position = 3;
        w4.Expand = false;
        w4.Fill = false;
        this.vbox4.Add(this.hbox3);
        Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox4[this.hbox3]));
        w5.Position = 0;
        w5.Expand = false;
        w5.Fill = false;
        // Container child vbox4.Gtk.Box+BoxChild
        this.RumbleToggle = new Gtk.ToggleButton();
        this.RumbleToggle.CanFocus = true;
        this.RumbleToggle.Name = "RumbleToggle";
        this.RumbleToggle.UseUnderline = true;
        this.RumbleToggle.Label = Mono.Unix.Catalog.GetString("Rumble");
        this.vbox4.Add(this.RumbleToggle);
        Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox4[this.RumbleToggle]));
        w6.Position = 1;
        w6.Expand = false;
        w6.Fill = false;
        this.hbox2.Add(this.vbox4);
        Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox2[this.vbox4]));
        w7.Position = 0;
        w7.Expand = false;
        w7.Fill = false;
        // Container child hbox2.Gtk.Box+BoxChild
        this.frame4 = new Gtk.Frame();
        this.frame4.Name = "frame4";
        this.frame4.ShadowType = ((Gtk.ShadowType)(4));
        // Container child frame4.Gtk.Container+ContainerChild
        this.GtkAlignment1 = new Gtk.Alignment(0F, 0F, 1F, 1F);
        this.GtkAlignment1.Name = "GtkAlignment1";
        this.GtkAlignment1.LeftPadding = ((uint)(12));
        // Container child GtkAlignment1.Gtk.Container+ContainerChild
        this.vbox2 = new Gtk.VBox();
        this.vbox2.Name = "vbox2";
        this.vbox2.Spacing = 6;
        // Container child vbox2.Gtk.Box+BoxChild
        this.hbox1 = new Gtk.HBox();
        this.hbox1.Name = "hbox1";
        this.hbox1.Spacing = 6;
        // Container child hbox1.Gtk.Box+BoxChild
        this.label1 = new Gtk.Label();
        this.label1.Name = "label1";
        this.label1.LabelProp = Mono.Unix.Catalog.GetString("X");
        this.hbox1.Add(this.label1);
        Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.hbox1[this.label1]));
        w8.Position = 0;
        w8.Expand = false;
        w8.Fill = false;
        // Container child hbox1.Gtk.Box+BoxChild
        this.XAccelBar = new Gtk.ProgressBar();
        this.XAccelBar.Name = "XAccelBar";
        this.hbox1.Add(this.XAccelBar);
        Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.hbox1[this.XAccelBar]));
        w9.Position = 1;
        this.vbox2.Add(this.hbox1);
        Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
        w10.Position = 0;
        w10.Expand = false;
        w10.Fill = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.hbox4 = new Gtk.HBox();
        this.hbox4.Name = "hbox4";
        this.hbox4.Spacing = 6;
        // Container child hbox4.Gtk.Box+BoxChild
        this.label3 = new Gtk.Label();
        this.label3.Name = "label3";
        this.label3.LabelProp = Mono.Unix.Catalog.GetString("Y");
        this.hbox4.Add(this.label3);
        Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.hbox4[this.label3]));
        w11.Position = 0;
        w11.Expand = false;
        w11.Fill = false;
        // Container child hbox4.Gtk.Box+BoxChild
        this.YAccelBar = new Gtk.ProgressBar();
        this.YAccelBar.Name = "YAccelBar";
        this.hbox4.Add(this.YAccelBar);
        Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.hbox4[this.YAccelBar]));
        w12.Position = 1;
        this.vbox2.Add(this.hbox4);
        Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox4]));
        w13.Position = 1;
        w13.Expand = false;
        w13.Fill = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.hbox5 = new Gtk.HBox();
        this.hbox5.Name = "hbox5";
        this.hbox5.Spacing = 6;
        // Container child hbox5.Gtk.Box+BoxChild
        this.label4 = new Gtk.Label();
        this.label4.Name = "label4";
        this.label4.LabelProp = Mono.Unix.Catalog.GetString("Z");
        this.hbox5.Add(this.label4);
        Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.hbox5[this.label4]));
        w14.Position = 0;
        w14.Expand = false;
        w14.Fill = false;
        // Container child hbox5.Gtk.Box+BoxChild
        this.ZAccelBar = new Gtk.ProgressBar();
        this.ZAccelBar.Name = "ZAccelBar";
        this.hbox5.Add(this.ZAccelBar);
        Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.hbox5[this.ZAccelBar]));
        w15.Position = 1;
        this.vbox2.Add(this.hbox5);
        Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox5]));
        w16.Position = 2;
        w16.Expand = false;
        w16.Fill = false;
        this.GtkAlignment1.Add(this.vbox2);
        this.frame4.Add(this.GtkAlignment1);
        this.GtkLabel8 = new Gtk.Label();
        this.GtkLabel8.Name = "GtkLabel8";
        this.GtkLabel8.LabelProp = Mono.Unix.Catalog.GetString("<b>Accelerometer Data</b>");
        this.GtkLabel8.UseMarkup = true;
        this.frame4.LabelWidget = this.GtkLabel8;
        this.hbox2.Add(this.frame4);
        Gtk.Box.BoxChild w19 = ((Gtk.Box.BoxChild)(this.hbox2[this.frame4]));
        w19.Position = 1;
        w19.Expand = false;
        w19.Fill = false;
        this.vbox1.Add(this.hbox2);
        Gtk.Box.BoxChild w20 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
        w20.Position = 0;
        w20.Expand = false;
        w20.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.statusbar1 = new Gtk.Statusbar();
        this.statusbar1.Name = "statusbar1";
        this.statusbar1.Spacing = 6;
        this.statusbar1.HasResizeGrip = false;
        // Container child statusbar1.Gtk.Box+BoxChild
        this.ButtonLabel = new Gtk.Label();
        this.ButtonLabel.Name = "ButtonLabel";
        this.ButtonLabel.LabelProp = Mono.Unix.Catalog.GetString("<no button>");
        this.statusbar1.Add(this.ButtonLabel);
        Gtk.Box.BoxChild w21 = ((Gtk.Box.BoxChild)(this.statusbar1[this.ButtonLabel]));
        w21.Position = 1;
        w21.Expand = false;
        w21.Fill = false;
        // Container child statusbar1.Gtk.Box+BoxChild
        this.StatusLabel = new Gtk.Label();
        this.StatusLabel.Name = "StatusLabel";
        this.StatusLabel.LabelProp = Mono.Unix.Catalog.GetString("Disconnected");
        this.statusbar1.Add(this.StatusLabel);
        Gtk.Box.BoxChild w22 = ((Gtk.Box.BoxChild)(this.statusbar1[this.StatusLabel]));
        w22.Position = 2;
        w22.Expand = false;
        w22.Fill = false;
        this.vbox1.Add(this.statusbar1);
        Gtk.Box.BoxChild w23 = ((Gtk.Box.BoxChild)(this.vbox1[this.statusbar1]));
        w23.PackType = ((Gtk.PackType)(1));
        w23.Position = 1;
        w23.Expand = false;
        w23.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.ConnectButton = new Gtk.Button();
        this.ConnectButton.CanFocus = true;
        this.ConnectButton.Name = "ConnectButton";
        this.ConnectButton.UseUnderline = true;
        this.ConnectButton.Label = Mono.Unix.Catalog.GetString("Connect");
        this.vbox1.Add(this.ConnectButton);
        Gtk.Box.BoxChild w24 = ((Gtk.Box.BoxChild)(this.vbox1[this.ConnectButton]));
        w24.PackType = ((Gtk.PackType)(1));
        w24.Position = 2;
        w24.Expand = false;
        w24.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.frame1 = new Gtk.Frame();
        this.frame1.Name = "frame1";
        this.frame1.ShadowType = ((Gtk.ShadowType)(4));
        // Container child frame1.Gtk.Container+ContainerChild
        this.GtkAlignment3 = new Gtk.Alignment(0F, 0F, 1F, 1F);
        this.GtkAlignment3.Name = "GtkAlignment3";
        this.GtkAlignment3.LeftPadding = ((uint)(12));
        // Container child GtkAlignment3.Gtk.Container+ContainerChild
        this.InfraRedArea = new Gtk.DrawingArea();
        this.InfraRedArea.Name = "InfraRedArea";
        this.GtkAlignment3.Add(this.InfraRedArea);
        this.frame1.Add(this.GtkAlignment3);
        this.GtkLabel7 = new Gtk.Label();
        this.GtkLabel7.Name = "GtkLabel7";
        this.GtkLabel7.LabelProp = Mono.Unix.Catalog.GetString("<b>IR Data</b>");
        this.GtkLabel7.UseMarkup = true;
        this.frame1.LabelWidget = this.GtkLabel7;
        this.vbox1.Add(this.frame1);
        Gtk.Box.BoxChild w27 = ((Gtk.Box.BoxChild)(this.vbox1[this.frame1]));
        w27.PackType = ((Gtk.PackType)(1));
        w27.Position = 3;
        this.GtkAlignment.Add(this.vbox1);
        this.frame2.Add(this.GtkAlignment);
        this.GtkLabel10 = new Gtk.Label();
        this.GtkLabel10.Name = "GtkLabel10";
        this.GtkLabel10.LabelProp = Mono.Unix.Catalog.GetString("<b>Remote</b>");
        this.GtkLabel10.UseMarkup = true;
        this.frame2.LabelWidget = this.GtkLabel10;
        this.hpaned1.Add(this.frame2);
        Gtk.Paned.PanedChild w30 = ((Gtk.Paned.PanedChild)(this.hpaned1[this.frame2]));
        w30.Resize = false;
        // Container child hpaned1.Gtk.Paned+PanedChild
        this.frame3 = new Gtk.Frame();
        this.frame3.Name = "frame3";
        this.frame3.ShadowType = ((Gtk.ShadowType)(4));
        // Container child frame3.Gtk.Container+ContainerChild
        this.GtkAlignment2 = new Gtk.Alignment(0F, 0F, 1F, 1F);
        this.GtkAlignment2.Name = "GtkAlignment2";
        this.GtkAlignment2.LeftPadding = ((uint)(12));
        // Container child GtkAlignment2.Gtk.Container+ContainerChild
        this.vbox3 = new Gtk.VBox();
        this.vbox3.Name = "vbox3";
        this.vbox3.Spacing = 6;
        // Container child vbox3.Gtk.Box+BoxChild
        this.frame5 = new Gtk.Frame();
        this.frame5.Name = "frame5";
        this.frame5.ShadowType = ((Gtk.ShadowType)(4));
        // Container child frame5.Gtk.Container+ContainerChild
        this.GtkAlignment4 = new Gtk.Alignment(0F, 0F, 1F, 1F);
        this.GtkAlignment4.Name = "GtkAlignment4";
        this.GtkAlignment4.LeftPadding = ((uint)(12));
        // Container child GtkAlignment4.Gtk.Container+ContainerChild
        this.vbox5 = new Gtk.VBox();
        this.vbox5.Name = "vbox5";
        this.vbox5.Spacing = 6;
        // Container child vbox5.Gtk.Box+BoxChild
        this.hbox6 = new Gtk.HBox();
        this.hbox6.Name = "hbox6";
        this.hbox6.Spacing = 6;
        // Container child hbox6.Gtk.Box+BoxChild
        this.label5 = new Gtk.Label();
        this.label5.Name = "label5";
        this.label5.LabelProp = Mono.Unix.Catalog.GetString("X");
        this.hbox6.Add(this.label5);
        Gtk.Box.BoxChild w31 = ((Gtk.Box.BoxChild)(this.hbox6[this.label5]));
        w31.Position = 0;
        w31.Expand = false;
        w31.Fill = false;
        // Container child hbox6.Gtk.Box+BoxChild
        this.NunchukXAccelBar = new Gtk.ProgressBar();
        this.NunchukXAccelBar.Name = "NunchukXAccelBar";
        this.hbox6.Add(this.NunchukXAccelBar);
        Gtk.Box.BoxChild w32 = ((Gtk.Box.BoxChild)(this.hbox6[this.NunchukXAccelBar]));
        w32.Position = 1;
        this.vbox5.Add(this.hbox6);
        Gtk.Box.BoxChild w33 = ((Gtk.Box.BoxChild)(this.vbox5[this.hbox6]));
        w33.Position = 0;
        w33.Expand = false;
        w33.Fill = false;
        // Container child vbox5.Gtk.Box+BoxChild
        this.hbox7 = new Gtk.HBox();
        this.hbox7.Name = "hbox7";
        this.hbox7.Spacing = 6;
        // Container child hbox7.Gtk.Box+BoxChild
        this.label6 = new Gtk.Label();
        this.label6.Name = "label6";
        this.label6.LabelProp = Mono.Unix.Catalog.GetString("Y");
        this.hbox7.Add(this.label6);
        Gtk.Box.BoxChild w34 = ((Gtk.Box.BoxChild)(this.hbox7[this.label6]));
        w34.Position = 0;
        w34.Expand = false;
        w34.Fill = false;
        // Container child hbox7.Gtk.Box+BoxChild
        this.NunchukYAccelBar = new Gtk.ProgressBar();
        this.NunchukYAccelBar.Name = "NunchukYAccelBar";
        this.hbox7.Add(this.NunchukYAccelBar);
        Gtk.Box.BoxChild w35 = ((Gtk.Box.BoxChild)(this.hbox7[this.NunchukYAccelBar]));
        w35.Position = 1;
        this.vbox5.Add(this.hbox7);
        Gtk.Box.BoxChild w36 = ((Gtk.Box.BoxChild)(this.vbox5[this.hbox7]));
        w36.Position = 1;
        w36.Expand = false;
        w36.Fill = false;
        // Container child vbox5.Gtk.Box+BoxChild
        this.hbox8 = new Gtk.HBox();
        this.hbox8.Name = "hbox8";
        this.hbox8.Spacing = 6;
        // Container child hbox8.Gtk.Box+BoxChild
        this.label7 = new Gtk.Label();
        this.label7.Name = "label7";
        this.label7.LabelProp = Mono.Unix.Catalog.GetString("Z");
        this.hbox8.Add(this.label7);
        Gtk.Box.BoxChild w37 = ((Gtk.Box.BoxChild)(this.hbox8[this.label7]));
        w37.Position = 0;
        w37.Expand = false;
        w37.Fill = false;
        // Container child hbox8.Gtk.Box+BoxChild
        this.NunchukZAccelBar = new Gtk.ProgressBar();
        this.NunchukZAccelBar.Name = "NunchukZAccelBar";
        this.hbox8.Add(this.NunchukZAccelBar);
        Gtk.Box.BoxChild w38 = ((Gtk.Box.BoxChild)(this.hbox8[this.NunchukZAccelBar]));
        w38.Position = 1;
        this.vbox5.Add(this.hbox8);
        Gtk.Box.BoxChild w39 = ((Gtk.Box.BoxChild)(this.vbox5[this.hbox8]));
        w39.Position = 2;
        w39.Expand = false;
        w39.Fill = false;
        this.GtkAlignment4.Add(this.vbox5);
        this.frame5.Add(this.GtkAlignment4);
        this.GtkLabel11 = new Gtk.Label();
        this.GtkLabel11.Name = "GtkLabel11";
        this.GtkLabel11.LabelProp = Mono.Unix.Catalog.GetString("<b>Accelerometer Data</b>");
        this.GtkLabel11.UseMarkup = true;
        this.frame5.LabelWidget = this.GtkLabel11;
        this.vbox3.Add(this.frame5);
        Gtk.Box.BoxChild w42 = ((Gtk.Box.BoxChild)(this.vbox3[this.frame5]));
        w42.Position = 0;
        w42.Expand = false;
        w42.Fill = false;
        // Container child vbox3.Gtk.Box+BoxChild
        this.frame6 = new Gtk.Frame();
        this.frame6.Name = "frame6";
        this.frame6.ShadowType = ((Gtk.ShadowType)(4));
        // Container child frame6.Gtk.Container+ContainerChild
        this.GtkAlignment6 = new Gtk.Alignment(0F, 0F, 1F, 1F);
        this.GtkAlignment6.Name = "GtkAlignment6";
        this.GtkAlignment6.LeftPadding = ((uint)(12));
        // Container child GtkAlignment6.Gtk.Container+ContainerChild
        this.NunchukStickArea = new Gtk.DrawingArea();
        this.NunchukStickArea.WidthRequest = 65;
        this.NunchukStickArea.HeightRequest = 65;
        this.NunchukStickArea.Name = "NunchukStickArea";
        this.GtkAlignment6.Add(this.NunchukStickArea);
        this.frame6.Add(this.GtkAlignment6);
        this.GtkLabel13 = new Gtk.Label();
        this.GtkLabel13.Name = "GtkLabel13";
        this.GtkLabel13.LabelProp = Mono.Unix.Catalog.GetString("<b>Stick Data</b>");
        this.GtkLabel13.UseMarkup = true;
        this.frame6.LabelWidget = this.GtkLabel13;
        this.vbox3.Add(this.frame6);
        Gtk.Box.BoxChild w45 = ((Gtk.Box.BoxChild)(this.vbox3[this.frame6]));
        w45.Position = 1;
        // Container child vbox3.Gtk.Box+BoxChild
        this.statusbar2 = new Gtk.Statusbar();
        this.statusbar2.Name = "statusbar2";
        this.statusbar2.Spacing = 6;
        this.statusbar2.HasResizeGrip = false;
        // Container child statusbar2.Gtk.Box+BoxChild
        this.NunchukButtonLabel = new Gtk.Label();
        this.NunchukButtonLabel.Name = "NunchukButtonLabel";
        this.NunchukButtonLabel.LabelProp = Mono.Unix.Catalog.GetString("<no button>");
        this.statusbar2.Add(this.NunchukButtonLabel);
        Gtk.Box.BoxChild w46 = ((Gtk.Box.BoxChild)(this.statusbar2[this.NunchukButtonLabel]));
        w46.Position = 1;
        w46.Expand = false;
        w46.Fill = false;
        // Container child statusbar2.Gtk.Box+BoxChild
        this.NunchukStatusLabel = new Gtk.Label();
        this.NunchukStatusLabel.Name = "NunchukStatusLabel";
        this.NunchukStatusLabel.LabelProp = Mono.Unix.Catalog.GetString("Disconnected");
        this.statusbar2.Add(this.NunchukStatusLabel);
        Gtk.Box.BoxChild w47 = ((Gtk.Box.BoxChild)(this.statusbar2[this.NunchukStatusLabel]));
        w47.Position = 2;
        w47.Expand = false;
        w47.Fill = false;
        this.vbox3.Add(this.statusbar2);
        Gtk.Box.BoxChild w48 = ((Gtk.Box.BoxChild)(this.vbox3[this.statusbar2]));
        w48.Position = 2;
        w48.Expand = false;
        this.GtkAlignment2.Add(this.vbox3);
        this.frame3.Add(this.GtkAlignment2);
        this.GtkLabel12 = new Gtk.Label();
        this.GtkLabel12.Name = "GtkLabel12";
        this.GtkLabel12.LabelProp = Mono.Unix.Catalog.GetString("<b>Nunchuk</b>");
        this.GtkLabel12.UseMarkup = true;
        this.frame3.LabelWidget = this.GtkLabel12;
        this.hpaned1.Add(this.frame3);
        this.Add(this.hpaned1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 778;
        this.DefaultHeight = 504;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.LED1Toggle.Toggled += new System.EventHandler(this.OnLED1Toggled);
        this.LED2Toggle.Toggled += new System.EventHandler(this.OnLED2Toggled);
        this.LED3Toggle.Toggled += new System.EventHandler(this.OnLED3Toggled);
        this.LED4Toggle.Toggled += new System.EventHandler(this.OnLED4Toggled);
        this.RumbleToggle.Toggled += new System.EventHandler(this.OnRumbleToggled);
        this.InfraRedArea.ExposeEvent += new Gtk.ExposeEventHandler(this.OnIRExpose);
        this.ConnectButton.Clicked += new System.EventHandler(this.OnConnectButtonClicked);
        this.NunchukStickArea.ExposeEvent += new Gtk.ExposeEventHandler(this.OnNunchukStickExposed);
    }
}
